import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Navigation } from "../components/Navigation";
import { Providers } from "@/components/Providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <div className="app-wrapper container h-screen mx-auto p-0 grid grid-cols-4 ">
            <Navigation />
            <main className="app-main p-0 overflow-hidden col-span-3">
              {children}
            </main>
          </div>
        </Providers>
      </body>
    </html>
  );
}
